image: alpine:3.8

before_script:
    - apk update && apk add bash git python py2-lxml rsync wget xz
    - git clone https://anongit.gentoo.org/git/proj/portage.git
    - cd portage && python setup.py install
    - cd repoman && python setup.py install
    - git clone https://gitlab.com/lramage94/gentoo.git /usr/portage
    - adduser -S portage && addgroup portage

test:
  stage: test
  script:
    - ARCH=x86_64 ACCEPT_KEYWORDS='' repoman -dxi full